POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

#######################

GET http://localhost:3001/dictionary/get-words
Content-Type: application/json
Authorization: Bearer 
Origin: http://localhost:3001

#######################

GET http://localhost:3001/training/get-amount-words-for-trainings
Content-Type: application/json
Authorization: Bearer 
Origin: http://localhost:3001
